// GENERATED by scripts/build-quran-data.mjs — do not edit by hand.
// Source: Tanzil Quran Text (Uthmani) — https://tanzil.net (see LICENSE.txt).

export type SurahMeta = {
  id: number
  nameAr: string
  nameEn: string
  ayahCount: number
}

export type SurahText = {
  surah: number
  basmala: string | null
  ayat: string[]
}

export const QURAN_SOURCE_MD5 = '7410caf5dc5b337de917b47ed887e3cb'
export const QURAN_DATASET_CHECKSUM = 'fnv1a-49059574'

export const SURAHS: SurahMeta[] = [
  { id: 1, nameAr: "الفاتحة", nameEn: "Al-Faatiha", ayahCount: 7 },
  { id: 2, nameAr: "البقرة", nameEn: "Al-Baqara", ayahCount: 286 },
  { id: 3, nameAr: "آل عمران", nameEn: "Aal-i-Imraan", ayahCount: 200 },
  { id: 4, nameAr: "النساء", nameEn: "An-Nisaa", ayahCount: 176 },
  { id: 5, nameAr: "المائدة", nameEn: "Al-Maaida", ayahCount: 120 },
  { id: 6, nameAr: "الأنعام", nameEn: "Al-An'aam", ayahCount: 165 },
  { id: 7, nameAr: "الأعراف", nameEn: "Al-A'raaf", ayahCount: 206 },
  { id: 8, nameAr: "الأنفال", nameEn: "Al-Anfaal", ayahCount: 75 },
  { id: 9, nameAr: "التوبة", nameEn: "At-Tawba", ayahCount: 129 },
  { id: 10, nameAr: "يونس", nameEn: "Yunus", ayahCount: 109 },
  { id: 11, nameAr: "هود", nameEn: "Hud", ayahCount: 123 },
  { id: 12, nameAr: "يوسف", nameEn: "Yusuf", ayahCount: 111 },
  { id: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", ayahCount: 43 },
  { id: 14, nameAr: "ابراهيم", nameEn: "Ibrahim", ayahCount: 52 },
  { id: 15, nameAr: "الحجر", nameEn: "Al-Hijr", ayahCount: 99 },
  { id: 16, nameAr: "النحل", nameEn: "An-Nahl", ayahCount: 128 },
  { id: 17, nameAr: "الإسراء", nameEn: "Al-Israa", ayahCount: 111 },
  { id: 18, nameAr: "الكهف", nameEn: "Al-Kahf", ayahCount: 110 },
  { id: 19, nameAr: "مريم", nameEn: "Maryam", ayahCount: 98 },
  { id: 20, nameAr: "طه", nameEn: "Taa-Haa", ayahCount: 135 },
  { id: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiyaa", ayahCount: 112 },
  { id: 22, nameAr: "الحج", nameEn: "Al-Hajj", ayahCount: 78 },
  { id: 23, nameAr: "المؤمنون", nameEn: "Al-Muminoon", ayahCount: 118 },
  { id: 24, nameAr: "النور", nameEn: "An-Noor", ayahCount: 64 },
  { id: 25, nameAr: "الفرقان", nameEn: "Al-Furqaan", ayahCount: 77 },
  { id: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'araa", ayahCount: 227 },
  { id: 27, nameAr: "النمل", nameEn: "An-Naml", ayahCount: 93 },
  { id: 28, nameAr: "القصص", nameEn: "Al-Qasas", ayahCount: 88 },
  { id: 29, nameAr: "العنكبوت", nameEn: "Al-Ankaboot", ayahCount: 69 },
  { id: 30, nameAr: "الروم", nameEn: "Ar-Room", ayahCount: 60 },
  { id: 31, nameAr: "لقمان", nameEn: "Luqman", ayahCount: 34 },
  { id: 32, nameAr: "السجدة", nameEn: "As-Sajda", ayahCount: 30 },
  { id: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzaab", ayahCount: 73 },
  { id: 34, nameAr: "سبإ", nameEn: "Saba", ayahCount: 54 },
  { id: 35, nameAr: "فاطر", nameEn: "Faatir", ayahCount: 45 },
  { id: 36, nameAr: "يس", nameEn: "Yaseen", ayahCount: 83 },
  { id: 37, nameAr: "الصافات", nameEn: "As-Saaffaat", ayahCount: 182 },
  { id: 38, nameAr: "ص", nameEn: "Saad", ayahCount: 88 },
  { id: 39, nameAr: "الزمر", nameEn: "Az-Zumar", ayahCount: 75 },
  { id: 40, nameAr: "غافر", nameEn: "Al-Ghaafir", ayahCount: 85 },
  { id: 41, nameAr: "فصلت", nameEn: "Fussilat", ayahCount: 54 },
  { id: 42, nameAr: "الشورى", nameEn: "Ash-Shura", ayahCount: 53 },
  { id: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", ayahCount: 89 },
  { id: 44, nameAr: "الدخان", nameEn: "Ad-Dukhaan", ayahCount: 59 },
  { id: 45, nameAr: "الجاثية", nameEn: "Al-Jaathiya", ayahCount: 37 },
  { id: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", ayahCount: 35 },
  { id: 47, nameAr: "محمد", nameEn: "Muhammad", ayahCount: 38 },
  { id: 48, nameAr: "الفتح", nameEn: "Al-Fath", ayahCount: 29 },
  { id: 49, nameAr: "الحجرات", nameEn: "Al-Hujuraat", ayahCount: 18 },
  { id: 50, nameAr: "ق", nameEn: "Qaaf", ayahCount: 45 },
  { id: 51, nameAr: "الذاريات", nameEn: "Adh-Dhaariyat", ayahCount: 60 },
  { id: 52, nameAr: "الطور", nameEn: "At-Tur", ayahCount: 49 },
  { id: 53, nameAr: "النجم", nameEn: "An-Najm", ayahCount: 62 },
  { id: 54, nameAr: "القمر", nameEn: "Al-Qamar", ayahCount: 55 },
  { id: 55, nameAr: "الرحمن", nameEn: "Ar-Rahmaan", ayahCount: 78 },
  { id: 56, nameAr: "الواقعة", nameEn: "Al-Waaqia", ayahCount: 96 },
  { id: 57, nameAr: "الحديد", nameEn: "Al-Hadid", ayahCount: 29 },
  { id: 58, nameAr: "المجادلة", nameEn: "Al-Mujaadila", ayahCount: 22 },
  { id: 59, nameAr: "الحشر", nameEn: "Al-Hashr", ayahCount: 24 },
  { id: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahana", ayahCount: 13 },
  { id: 61, nameAr: "الصف", nameEn: "As-Saff", ayahCount: 14 },
  { id: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'a", ayahCount: 11 },
  { id: 63, nameAr: "المنافقون", nameEn: "Al-Munaafiqoon", ayahCount: 11 },
  { id: 64, nameAr: "التغابن", nameEn: "At-Taghaabun", ayahCount: 18 },
  { id: 65, nameAr: "الطلاق", nameEn: "At-Talaaq", ayahCount: 12 },
  { id: 66, nameAr: "التحريم", nameEn: "At-Tahrim", ayahCount: 12 },
  { id: 67, nameAr: "الملك", nameEn: "Al-Mulk", ayahCount: 30 },
  { id: 68, nameAr: "القلم", nameEn: "Al-Qalam", ayahCount: 52 },
  { id: 69, nameAr: "الحاقة", nameEn: "Al-Haaqqa", ayahCount: 52 },
  { id: 70, nameAr: "المعارج", nameEn: "Al-Ma'aarij", ayahCount: 44 },
  { id: 71, nameAr: "نوح", nameEn: "Nooh", ayahCount: 28 },
  { id: 72, nameAr: "الجن", nameEn: "Al-Jinn", ayahCount: 28 },
  { id: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", ayahCount: 20 },
  { id: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", ayahCount: 56 },
  { id: 75, nameAr: "القيامة", nameEn: "Al-Qiyaama", ayahCount: 40 },
  { id: 76, nameAr: "الانسان", nameEn: "Al-Insaan", ayahCount: 31 },
  { id: 77, nameAr: "المرسلات", nameEn: "Al-Mursalaat", ayahCount: 50 },
  { id: 78, nameAr: "النبإ", nameEn: "An-Naba", ayahCount: 40 },
  { id: 79, nameAr: "النازعات", nameEn: "An-Naazi'aat", ayahCount: 46 },
  { id: 80, nameAr: "عبس", nameEn: "Abasa", ayahCount: 42 },
  { id: 81, nameAr: "التكوير", nameEn: "At-Takwir", ayahCount: 29 },
  { id: 82, nameAr: "الإنفطار", nameEn: "Al-Infitaar", ayahCount: 19 },
  { id: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", ayahCount: 36 },
  { id: 84, nameAr: "الإنشقاق", nameEn: "Al-Inshiqaaq", ayahCount: 25 },
  { id: 85, nameAr: "البروج", nameEn: "Al-Burooj", ayahCount: 22 },
  { id: 86, nameAr: "الطارق", nameEn: "At-Taariq", ayahCount: 17 },
  { id: 87, nameAr: "الأعلى", nameEn: "Al-A'laa", ayahCount: 19 },
  { id: 88, nameAr: "الغاشية", nameEn: "Al-Ghaashiya", ayahCount: 26 },
  { id: 89, nameAr: "الفجر", nameEn: "Al-Fajr", ayahCount: 30 },
  { id: 90, nameAr: "البلد", nameEn: "Al-Balad", ayahCount: 20 },
  { id: 91, nameAr: "الشمس", nameEn: "Ash-Shams", ayahCount: 15 },
  { id: 92, nameAr: "الليل", nameEn: "Al-Lail", ayahCount: 21 },
  { id: 93, nameAr: "الضحى", nameEn: "Ad-Dhuhaa", ayahCount: 11 },
  { id: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", ayahCount: 8 },
  { id: 95, nameAr: "التين", nameEn: "At-Tin", ayahCount: 8 },
  { id: 96, nameAr: "العلق", nameEn: "Al-Alaq", ayahCount: 19 },
  { id: 97, nameAr: "القدر", nameEn: "Al-Qadr", ayahCount: 5 },
  { id: 98, nameAr: "البينة", nameEn: "Al-Bayyina", ayahCount: 8 },
  { id: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzala", ayahCount: 8 },
  { id: 100, nameAr: "العاديات", nameEn: "Al-Aadiyaat", ayahCount: 11 },
  { id: 101, nameAr: "القارعة", nameEn: "Al-Qaari'a", ayahCount: 11 },
  { id: 102, nameAr: "التكاثر", nameEn: "At-Takaathur", ayahCount: 8 },
  { id: 103, nameAr: "العصر", nameEn: "Al-Asr", ayahCount: 3 },
  { id: 104, nameAr: "الهمزة", nameEn: "Al-Humaza", ayahCount: 9 },
  { id: 105, nameAr: "الفيل", nameEn: "Al-Fil", ayahCount: 5 },
  { id: 106, nameAr: "قريش", nameEn: "Quraish", ayahCount: 4 },
  { id: 107, nameAr: "الماعون", nameEn: "Al-Maa'un", ayahCount: 7 },
  { id: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", ayahCount: 3 },
  { id: 109, nameAr: "الكافرون", nameEn: "Al-Kaafiroon", ayahCount: 6 },
  { id: 110, nameAr: "النصر", nameEn: "An-Nasr", ayahCount: 3 },
  { id: 111, nameAr: "المسد", nameEn: "Al-Masad", ayahCount: 5 },
  { id: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlaas", ayahCount: 4 },
  { id: 113, nameAr: "الفلق", nameEn: "Al-Falaq", ayahCount: 5 },
  { id: 114, nameAr: "الناس", nameEn: "An-Naas", ayahCount: 6 },
]

const modules = import.meta.glob<SurahText>('./*.json', {
  import: 'default',
})

export function loadSurah(id: number): Promise<SurahText> {
  const key = `./${String(id).padStart(3, '0')}.json`
  const load = modules[key]
  if (!load) return Promise.reject(new Error('unknown-surah'))
  return load()
}
