/**
 * Templates are data, not code. A template is a cohesive art direction —
 * palette, background, ornament set, typography pairing, and a layout variant
 * — and the design system is the whole catalog of them. Thumbnails are
 * rendered from the *real* engine so a preview can never lie.
 */

export type PaletteId = 'parchment' | 'forest' | 'night' | 'sand' | 'dusk'
export type BackgroundId = 'paper' | 'glow' | 'lattice' | 'girih' | 'arches'
export type OrnamentSetId = 'minimal' | 'flourish' | 'mihrab' | 'border'
export type FrameId = 'square' | 'portrait' | 'story'
export type LayoutVariant = 'classic' | 'feature'

export type FontId = 'body' | 'display'

export type Template = {
  id: string
  family: 'parchment' | 'night' | 'minimal' | 'calligraphic'
  nameEn: string
  nameAr: string
  palette: PaletteId
  background: BackgroundId
  ornaments: OrnamentSetId
  layout: LayoutVariant
  /** Font family per role. Two licensed faces only (body + display). */
  fonts: { body: FontId; display: FontId }
  /** Arabic line-height multiplier (Uthmani wants ~1.9–2.1). */
  lineHeight: number
  /** Minimum Arabic size per frame — the legibility floor. */
  minArabic: Record<FrameId, number>
  labelSize: number
  citationSize: number
  footerSize: number
}

export const TEMPLATES: Template[] = [
  {
    id: 'parchment-classic',
    family: 'parchment',
    nameEn: 'Parchment classic',
    nameAr: 'كلاسيكي ورقي',
    palette: 'parchment',
    background: 'paper',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'parchment-flourish',
    family: 'parchment',
    nameEn: 'Parchment flourish',
    nameAr: 'ورقي مزخرف',
    palette: 'parchment',
    background: 'girih',
    ornaments: 'flourish',
    layout: 'feature',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.95,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'parchment-arches',
    family: 'parchment',
    nameEn: 'Parchment arches',
    nameAr: 'ورقي بأقواس',
    palette: 'sand',
    background: 'arches',
    ornaments: 'mihrab',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'forest-classic',
    family: 'parchment',
    nameEn: 'Forest classic',
    nameAr: 'غابة كلاسيكي',
    palette: 'forest',
    background: 'glow',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'forest-lattice',
    family: 'parchment',
    nameEn: 'Forest lattice',
    nameAr: 'غابة بشبك',
    palette: 'forest',
    background: 'lattice',
    ornaments: 'border',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.95,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'night-mushaf',
    family: 'night',
    nameEn: 'Night mushaf',
    nameAr: 'مصحف ليلي',
    palette: 'night',
    background: 'glow',
    ornaments: 'mihrab',
    layout: 'feature',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 2,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'night-border',
    family: 'night',
    nameEn: 'Night border',
    nameAr: 'ليلي بإطار',
    palette: 'night',
    background: 'lattice',
    ornaments: 'border',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.95,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'dusk-girih',
    family: 'night',
    nameEn: 'Dusk girih',
    nameAr: 'غسقي بزخرفة',
    palette: 'dusk',
    background: 'girih',
    ornaments: 'flourish',
    layout: 'feature',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.95,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'dusk-arches',
    family: 'night',
    nameEn: 'Dusk arches',
    nameAr: 'غسقي بأقواس',
    palette: 'dusk',
    background: 'arches',
    ornaments: 'mihrab',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'minimal-editorial',
    family: 'minimal',
    nameEn: 'Minimal editorial',
    nameAr: 'تحريري بسيط',
    palette: 'parchment',
    background: 'paper',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.75,
    minArabic: { square: 26, portrait: 28, story: 30 },
    labelSize: 28,
    citationSize: 24,
    footerSize: 22,
  },
  {
    id: 'minimal-night',
    family: 'minimal',
    nameEn: 'Minimal night',
    nameAr: 'بسيط ليلي',
    palette: 'night',
    background: 'paper',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.75,
    minArabic: { square: 26, portrait: 28, story: 30 },
    labelSize: 28,
    citationSize: 24,
    footerSize: 22,
  },
  {
    id: 'calligraphic-display',
    family: 'calligraphic',
    nameEn: 'Calligraphic',
    nameAr: 'خطي',
    palette: 'sand',
    background: 'glow',
    ornaments: 'flourish',
    layout: 'feature',
    fonts: { body: 'display', display: 'display' },
    lineHeight: 2.05,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'calligraphic-mihrab',
    family: 'calligraphic',
    nameEn: 'Calligraphic mihrab',
    nameAr: 'محراب خطي',
    palette: 'forest',
    background: 'arches',
    ornaments: 'mihrab',
    layout: 'classic',
    fonts: { body: 'display', display: 'display' },
    lineHeight: 2,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'sand-lattice',
    family: 'parchment',
    nameEn: 'Sand lattice',
    nameAr: 'رملي بشبك',
    palette: 'sand',
    background: 'lattice',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'sand-girih',
    family: 'parchment',
    nameEn: 'Sand girih',
    nameAr: 'رملي بزخرفة',
    palette: 'sand',
    background: 'girih',
    ornaments: 'flourish',
    layout: 'feature',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.95,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'forest-arches',
    family: 'parchment',
    nameEn: 'Forest arches',
    nameAr: 'غابة بأقواس',
    palette: 'forest',
    background: 'arches',
    ornaments: 'mihrab',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.9,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'night-arches',
    family: 'night',
    nameEn: 'Night arches',
    nameAr: 'ليلي بأقواس',
    palette: 'night',
    background: 'arches',
    ornaments: 'mihrab',
    layout: 'feature',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 2,
    minArabic: { square: 24, portrait: 26, story: 28 },
    labelSize: 30,
    citationSize: 26,
    footerSize: 24,
  },
  {
    id: 'dusk-minimal',
    family: 'night',
    nameEn: 'Dusk minimal',
    nameAr: 'غسقي بسيط',
    palette: 'dusk',
    background: 'paper',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 1.8,
    minArabic: { square: 26, portrait: 28, story: 30 },
    labelSize: 28,
    citationSize: 24,
    footerSize: 22,
  },
  {
    id: 'long-verse',
    family: 'minimal',
    nameEn: 'Long verse',
    nameAr: 'آية طويلة',
    palette: 'parchment',
    background: 'paper',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    // Tuned for the longest ayah (2:282): smaller floor, wider leading.
    lineHeight: 2.1,
    minArabic: { square: 20, portrait: 22, story: 24 },
    labelSize: 28,
    citationSize: 24,
    footerSize: 22,
  },
  {
    id: 'long-verse-night',
    family: 'night',
    nameEn: 'Long verse night',
    nameAr: 'آية طويلة ليلية',
    palette: 'night',
    background: 'glow',
    ornaments: 'minimal',
    layout: 'classic',
    fonts: { body: 'body', display: 'display' },
    lineHeight: 2.1,
    minArabic: { square: 20, portrait: 22, story: 24 },
    labelSize: 28,
    citationSize: 24,
    footerSize: 22,
  },
]

export const DEFAULT_TEMPLATE_ID = 'parchment-classic'

export function getTemplate(id: string): Template {
  return TEMPLATES.find((template) => template.id === id) ?? TEMPLATES[0]!
}

export function isValidTemplateId(id: string): boolean {
  return TEMPLATES.some((template) => template.id === id)
}
